from typing import Any, Protocol


class Pipeline(Protocol):
    """Every feature (score, critique, tailor, cover letter) follows this path."""

    def validate(self, request: Any) -> None: ...
    def retrieve_context(self, request: Any) -> list[Any]: ...
    def build_prompt(self, request: Any, context: list[Any]) -> str: ...
    def call_llm(self, prompt: str) -> Any: ...
    def parse_output(self, response: Any) -> Any: ...
    def run(self, request: Any) -> Any: ...
